[project]
name = "x-bookmarks"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28.1",
    "ollama>=0.6.1",
    "python-dotenv>=1.2.1",
    "rich>=14.3.3",
]
